name: Build and push to ACR

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Decode Base64 Secret to Environment Variable
        id: decode
        run: |
          echo "AZ_CREDS=$(echo '${{ secrets.AZURE_CREDENTIALS_BASE64 }}' | base64 --decode)" >> $GITHUB_ENV

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ env.AZ_CREDS }}

      - name: Set Container App Registry Credentials
        run: |
          az containerapp registry set \
            --name neal-api \
            --resource-group ai-governance-demo \
            --server nealregistry.azurecr.io \
            --username $(az acr credential show --name nealregistry --query "username" -o tsv) \
            --password $(az acr credential show --name nealregistry --query "passwords[0].value" -o tsv)

      - name: Log in to ACR
        run: az acr login --name nealregistry

      - name: Build and push UI Docker image
        run: |
          docker build -f Dockerfile.ui -t nealregistry.azurecr.io/ui:latest .
          docker push nealregistry.azurecr.io/ui:latest

      - name: Build and push API Docker image
        run: |
          docker build -f Dockerfile.api -t nealregistry.azurecr.io/fastapi-azure:latest .
          docker push nealregistry.azurecr.io/fastapi-azure:latest

      - name: Deploy API to Azure Container App
        run: |
          az containerapp update \
            --name neal-api \
            --resource-group ai-governance-demo \
            --image nealregistry.azurecr.io/fastapi-azure:latest

      - name: Set UI Container App Registry Credentials
        run: |
          az containerapp registry set \
            --name neal-ui \
            --resource-group ai-governance-demo \
            --server nealregistry.azurecr.io \
            --username $(az acr credential show --name nealregistry --query "username" -o tsv) \
            --password $(az acr credential show --name nealregistry --query "passwords[0].value" -o tsv)

      - name: Deploy UI to Azure Container App
        run: |
          API_URL=$(az containerapp show \
            --name neal-api \
            --resource-group ai-governance-demo \
            --query properties.configuration.ingress.fqdn \
            -o tsv)

          az containerapp update \
            --name neal-ui \
            --resource-group ai-governance-demo \
            --image nealregistry.azurecr.io/ui:latest \
            --set-env-vars API_URL=https://$API_URL
