name: Build and push to ACR

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure CLI login and ACR login
        uses: azure/cli@v1
        with:
          inlineScript: |
            az login --service-principal \
              --username ${{ secrets.AZURE_CLIENT_ID }} \
              --password ${{ secrets.AZURE_CLIENT_SECRET }} \
              --tenant ${{ secrets.AZURE_TENANT_ID }}

            az acr login --name nealregistry

      - name: Build and push Docker image
        run: |
          docker build -t nealregistry.azurecr.io/sample/fastapi-azure:latest .
          docker push nealregistry.azurecr.io/sample/fastapi-azure:latest

      - name: Deploy latest image to Azure Container App
        uses: azure/cli@v1
        with:
          inlineScript: |
            az login --service-principal \
              --username ${{ secrets.AZURE_CLIENT_ID }} \
              --password ${{ secrets.AZURE_CLIENT_SECRET }} \
              --tenant ${{ secrets.AZURE_TENANT_ID }}

            az containerapp update \
              --name neal-api \
              --resource-group ai-governance-demo \
              --image nealregistry.azurecr.io/sample/fastapi-azure:latest \
              --no-wait
