name: Build and push to ACR

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to ACR
        run: az acr login --name nealregistry

      - name: Build and push Docker image
        run: |
          docker build -t nealregistry.azurecr.io/sample/fastapi-azure:latest .
          docker push nealregistry.azurecr.io/sample/fastapi-azure:latest

      - name: Deploy to Azure Container App
        run: |
          az containerapp update \
            --name neal-api \
            --resource-group ai-governance-demo \
            --image nealregistry.azurecr.io/sample/fastapi-azure:latest
